### ISSUE TITLE
Can not open some jbig2 image

### ISSUE THREAD

**Issue by Charltsing** [winkingsoftware/JBig2Decoder.NETCore#6]
IndexOutOfRangeException
or
NullReferenceException

[error.zip](https://github.com/winkingsoftware/JBig2Decoder.NETCore/files/11371637/error.zip)

**Comment by Matti-Koopa** [comment]
Same here. File see attachment.
Stacktrace:
   `at JBig2Decoder.NETStandard.TextRegionSegment.ReadSegment() in JBig2Decoder.NETStandard\TextRegionSegment.cs:line 51`

Basically, `segment` is null here but not checked for null:
```
Segment segment = decoder.FindSegment(referredToSegments[i]);
if (segment.GetSegmentHeader().GetSegmentType() == 0)
```

[pdf-stream11-0.zip](https://github.com/user-attachments/files/16978689/pdf-stream11-0.zip)

**Comment by nicholsab** [comment]
We fixed this problem in: https://www.nuget.org/packages/JBig2Decoder.NETStandard/
Your test file pdf-stream11-0.jbig2 works correctly with it.

**Comment by Matti-Koopa** [comment]
This doesn't seem fixed to me. I extract the image from a PDF. This is the PDF: 
[1082193-2021-10.pdf](https://github.com/user-attachments/files/16981848/1082193-2021-10.pdf)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at JBig2Decoder.NETStandard.TextRegionSegment.ReadSegment()
   at JBig2Decoder.NETStandard.JBIG2StreamDecoder.ReadSegments()
   at JBig2Decoder.NETStandard.JBIG2StreamDecoder.DecodeJBIG2(Byte[] data, Int32& width, Int32& height)
   ```
How I use it (with UglyToad PdfPig NuGet): 
```
using PdfDocument pdfDocument = PdfDocument.Open(bytes, new ParsingOptions());
pdfDocument.GetPages()
page.GetImages()
image.RawMemory
byte[] output = new JBIG2StreamDecoder().DecodeJBIG2(bytes, out int width, out int height);
```
It's the second picture in the PDF.

**Comment by nicholsab** [comment]
This is the picture that is created from that pdf-stream11-0.jbig2, using ImageSharp to save as a png, and there are no exceptions.  Maybe the pdf is doing something with rotation and color changes.

Also, in that example you have variable `bytes` in the PDFDocument.Open and `bytes` in the DecodeJBIG2, is that on purpose?

![pic](https://github.com/user-attachments/assets/40d649a5-d935-426e-b407-ec6d3cdbfda8)
